classes/urls.py
from django.urls import path, re_path
from classes import views

app_name = 'classes'

urlpatterns = [
    path('list/', views.ClassListView.as_view(), name='class-list'),
    re_path(r'^(?P<class_name>[-\w]+)$', views.ClassDetailView.as_view(), name='class-detail'),
    path('create/', views.ClassCreateView.as_view(), name='class-create'),
    re_path(r'^(?P<class_name>[-\w]+)/update/$', views.ClassUpdateView.as_view(), name='class-update'),
    re_path(r'^(?P<class_name>[-\w]+)/delete/$', views.ClassDeleteView.as_view(), name='class-delete'),

    re_path(r'^(?P<class_name>[-\w]+)/addstudent/$', views.ClassDetailStudentCreate.as_view(), name='class-student-create'),
    path('deletestudent/<int:pk>', views.ClassDetailStudentDelete.as_view(), name='class-student-delete'),
    path('updatestudent/<int:pk>', views.ClassDetailStudentUpdate.as_view(), name='class-student-update'),
]

django_school_management_system/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordChangeView, PasswordResetDoneView, PasswordResetConfirmView
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

from dashboard.forms import ResetPasswordForm, PasswordChangeForm, SetPasswordForm
from dashboard.views import registeruser, editprofile, loginrequest

urlpatterns = [
    path('admin/', admin.site.urls),
    path("login/", loginrequest, name="loginrequest"),
    path("register/", registeruser, name="register"),
    path('editprofile/', editprofile, name='editprofile'),
    path('changepassword/', PasswordChangeView.as_view(template_name='registration/changepassword.html', form_class=PasswordChangeForm, success_url=reverse_lazy('dashboard:dashboard')), name='changepassword'),
    path('passwordreset/', PasswordResetView.as_view(template_name='registration/resetpassword.html', form_class=ResetPasswordForm, success_url=reverse_lazy('passwordresetsendmail')), name='resetpassword'),
    path('passwordresetmail/', PasswordResetDoneView.as_view(template_name='registration/sendmailnoti.html'), name='passwordresetsendmail'),
    path('setnewpassword/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/setnewpassword.html', form_class=SetPasswordForm, success_url=reverse_lazy('password_reset_complete')), name='setnewpassword'),

    path('results/', include('result.urls')),
    path('subjects/', include('subjects.urls')),
    path('students/', include('student.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('classes/', include('classes.urls')),
    path('teachers/', include('teachers.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='dashboard/', permanent=True)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

result/urls.py
from django.urls import path, re_path
from result import views

app_name = 'results'

urlpatterns = [
    path('subjectscore/<int:pk>/update/', views.SubjectScoreUpdate.as_view(), name='subject-score-update'),
    path('subjectscore/<int:pk>/delete/', views.SubjectScoreDelete.as_view(), name='subject-score-delete'),
]

student/urls.py
from django.urls import path

from student.views import StudentListView, StudentCreateView, StudentUpdateView, StudentDeleteView, StudentDetailView
from result.views import SubjectScoreCreat

app_name = 'students'

urlpatterns = [
    path('list/', StudentListView.as_view(), name='student_list'),
    path('<int:pk>', StudentDetailView.as_view(), name='student-detail'),
    path('create/', StudentCreateView.as_view(), name='student_create'),
    path('update/<int:pk>', StudentUpdateView.as_view(), name='student_update'),
    path('delete/<int:pk>', StudentDeleteView.as_view(), name='student_delete'),

    path('<int:pk>/addscore/', SubjectScoreCreat.as_view(), name='subject-score-create'),
]

subjects/urls.py
from django.urls import path

from subjects.views import SubjectListView, SubjectDetailView, SubjectCreateView, SubjectUpdateView, SubjectDeleteView

app_name = 'subjects'

urlpatterns = [
    path('', SubjectListView.as_view(), name='subject_list'),
    path('<int:pk>', SubjectDetailView.as_view(), name='subject-detail'),
    path('create/', SubjectCreateView.as_view(), name='subject_create'),
    path('update/<int:pk>', SubjectUpdateView.as_view(), name='subject_update'),
    path('delete/<int:pk>', SubjectDeleteView.as_view(), name='subject_delete'),
]

student/models.py
from datetime import date

import django.utils.timezone
from django.db import models

# Create your models here.
from django.urls import reverse

from classes.models import Class


class Student(models.Model):
    GENDER_CHOICES = (
        ('Nam', 'Nam'),
        ('Nu', 'Nu'),
        ('Khac', 'Khac'),
    )

    student_lastname = models.CharField('Ho va ten dem', max_length=80)
    student_firstname = models.CharField('Ten', max_length=50)
    student_gender = models.CharField('Gioi tinh', max_length=10, choices=GENDER_CHOICES, blank=True, default='Nam')
    student_class = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True, verbose_name='Lop')
    student_email = models.EmailField('Email', blank=True)
    student_date_of_birth = models.DateField('Ngay sinh', default=django.utils.timezone.now)
    student_reg = models.DateField(auto_now_add=True, auto_now=False)

    class Meta:
        ordering = ['student_class', 'student_firstname']

    def __str__(self):
        return f'{self.student_lastname} {self.student_firstname}'

    def get_absolute_url(self):
        """Returns the url to access a particular classes instance."""
        return reverse('students:student-detail', args=[str(self.id)])

subjects/models.py
from django.db import models


# Create your models here.


class Subject(models.Model):
    subject = models.CharField('Ten mon hoc', max_length=40, unique=True, error_messages={'unique':"Mon hoc nay da ton tai"})
    subject_unit = models.IntegerField('So tiet hoc', blank=True, null=True)

    def __str__(self):
        return self.subject


class Khoa(models.Model):
    department = models.CharField('Ten khoa', max_length=40, unique=True, error_messages={'unique':"Khoa nay da ton tai"})

    def __str__(self):
        return self.department

subjects/forms.py
from django import forms
from django.forms import ModelForm

from subjects.models import Subject, Khoa


class SubjectForm(ModelForm):
    class Meta:
        model = Subject
        fields = '__all__'
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'subject_unit': forms.NumberInput(attrs={'class': 'form-control form-control-user'}),
        }


class DepartmentForm(ModelForm):
    class Meta:
        model = Khoa
        fields = '__all__'
        widgets = {
            'department': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
        }

subjects/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from subjects.forms import SubjectForm
from subjects.models import Subject


class SubjectListView(ListView):
    model = Subject
    template_name = 'subject_list.html'


class SubjectDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    permission_required = 'subjects.view_subject'
    model = Subject
    template_name = 'subject_detail.html'


class SubjectCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'subjects.add_subject'
    template_name = 'subject_form.html'
    model = Subject
    form_class = SubjectForm


class SubjectDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'subjects.delete_subject'
    model = Subject
    template_name = 'subject_confirm_delete.html'
    success_url = reverse_lazy('subjects:subject_list')


class SubjectUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'subjects.change_subject'
    model = Subject
    form_class = SubjectForm
    template_name = 'subject_update.html'
    success_url = reverse_lazy('subjects:subject_list')

subjects/templates/subject_confirm_delete.html
{% extends "base.html" %}

{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h4 class="m-0 font-weight-bold text-primary">Xoa mon hoc?</h4>
        </div>
        <div class="card-body">
            <p>Ban muon xoa mon hoc {{ subject }}?</p>
            <form action="" method="post">
                {% csrf_token %}
                <table>
                {{ form.as_table }}
                </table>
                <input type="submit" value="Xoa" class="btn btn-primary btn-user">
            </form>
        </div>
    </div>

{% endblock %}

subjects/templates/subject_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>lop {{ class.class_name }}</title>
{% endblock %}

{% block header_static %}
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Lop {{ class.class_name }}</h1>
        <p class="mb-4">Giao vien chu nhiem: {% if class.giao_vien_CN %}{{ class.giao_vien_CN }}{% else %}Khong{% endif %}</p>
        <p class="mb-4">Si so: {{ class.student_set.all.count }}</p>
        {% if perms.student.add_student %}
        <a class="mb-4" href="{% url 'students:student_create' %}">Them hoc sinh</a>
        {% endif %}

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Ho va ten dem</th>
                                <th>Ten</th>
                                <th>Gioi tinh</th>
                                <th>Ngay sinh</th>
                                <th>Bang diem</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>ID</th>
                                <th>Ho va ten dem</th>
                                <th>Ten</th>
                                <th>Gioi tinh</th>
                                <th>Ngay sinh</th>
                                <th>Bang diem</th>
                                <th></th>
                            </tr>
                        </tfoot>
                        <tbody>
                            {% for student in class.student_set.all %}
                            <tr>
                            <td>{{ student.id }}</td>
                            <td>{{ student.student_lastname }}</td>
                            <td>{{ student.student_firstname }}</td>
                            <td>{{ student.student_gender }}</td>
                            <td>{{ student.student_date_of_birth|date:"d-m-Y" }}</td>
                            <td><a href="{% url 'students:student-detail' student.id %}">Chi tiet</a> </td>
{#                            <td><a href="{% url 'classes:class-update' student.id %}">Cap nhat</a> | <a href="#">Xoa</a></td>#}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer_static %}
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
{% endblock %}

subjects/templates/subject_form.html
{% extends "base.html" %}

{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h4 class="m-0 font-weight-bold text-primary">Them mon hoc</h4>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                <table>
                {{ form.as_table }}
                </table>
                <input type="submit" value="Them" class="btn btn-primary btn-user">
            </form>
        </div>
    </div>

{% endblock %}

subjects/templates/subject_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Danh sach lop hoc</title>
{% endblock %}

{% block header_static %}
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Danh sach mon hoc</h1>
        <p class="mb-4">Tong so mon hoc: {{ subject_list.count }}</p>

        {% if perms.subjects.add_subject %}
        <a class="collapse-item" href="{% url 'subjects:subject_create' %}">Them mon hoc</a>
        {% endif %}

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Mon hoc</th>
                                <th>So tiet hoc</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for subject in subject_list %}
                        <tr>
                            <td>{{ subject.id }}</td>
                            <td>{{ subject.subject }}</td>
                            <td>{{ subject.subject_unit }}</td>
                            <td>{% if perms.subjects.change_subject %}<a class="" href="{% url 'subjects:subject_update' subject.id %}">Cap nhat</a>{% endif %} {% if perms.subjects.delete_subject %}| <a class="" href="{% url 'subjects:subject_delete' subject.id %}">Xoa</a>{% endif %}
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer_static %}
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
{% endblock %}

subjects/templates/subject_update.html
{% extends "base.html" %}

{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h4 class="m-0 font-weight-bold text-primary">Cap nhat thong tin lop {{ class.class_name }}</h4>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                <table>
                {{ form.as_table }}
                </table>
                <a class="btn btn-primary btn-user" href="#" data-toggle="modal" data-target="#UpdateModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Cap nhat
                </a>

                <!-- Confirm Update Modal-->
                <div class="modal fade" id="UpdateModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Xac nhan cap nhat</h5>
                                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                            <div class="modal-body">Cap nhat thong tin lop {{ class.class_name }}</div>
                            <div class="modal-footer">
                                <button class="btn btn-secondary" type="button" data-dismiss="modal">Huy</button>
                                <input type="submit" value="Cap nhat" class="btn btn-primary btn-user">
                            </div>
                        </div>
                    </div>
                </div>

            </form>
        </div>
    </div>


{% endblock %}