classes/urls.py
from django.urls import path, re_path
from classes import views

app_name = 'classes'

urlpatterns = [
    path('list/', views.ClassListView.as_view(), name='class-list'),
    re_path(r'^(?P<class_name>[-\w]+)$', views.ClassDetailView.as_view(), name='class-detail'),
    path('create/', views.ClassCreateView.as_view(), name='class-create'),
    re_path(r'^(?P<class_name>[-\w]+)/update/$', views.ClassUpdateView.as_view(), name='class-update'),
    re_path(r'^(?P<class_name>[-\w]+)/delete/$', views.ClassDeleteView.as_view(), name='class-delete'),

    re_path(r'^(?P<class_name>[-\w]+)/addstudent/$', views.ClassDetailStudentCreate.as_view(), name='class-student-create'),
    path('deletestudent/<int:pk>', views.ClassDetailStudentDelete.as_view(), name='class-student-delete'),
    path('updatestudent/<int:pk>', views.ClassDetailStudentUpdate.as_view(), name='class-student-update'),
]

django_school_management_system/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordChangeView, PasswordResetDoneView, PasswordResetConfirmView
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

from dashboard.forms import ResetPasswordForm, PasswordChangeForm, SetPasswordForm
from dashboard.views import registeruser, editprofile, loginrequest

urlpatterns = [
    path('admin/', admin.site.urls),
    path("login/", loginrequest, name="loginrequest"),
    path("register/", registeruser, name="register"),
    path('editprofile/', editprofile, name='editprofile'),
    path('changepassword/', PasswordChangeView.as_view(template_name='registration/changepassword.html', form_class=PasswordChangeForm, success_url=reverse_lazy('dashboard:dashboard')), name='changepassword'),
    path('passwordreset/', PasswordResetView.as_view(template_name='registration/resetpassword.html', form_class=ResetPasswordForm, success_url=reverse_lazy('passwordresetsendmail')), name='resetpassword'),
    path('passwordresetmail/', PasswordResetDoneView.as_view(template_name='registration/sendmailnoti.html'), name='passwordresetsendmail'),
    path('setnewpassword/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/setnewpassword.html', form_class=SetPasswordForm, success_url=reverse_lazy('password_reset_complete')), name='setnewpassword'),

    path('results/', include('result.urls')),
    path('subjects/', include('subjects.urls')),
    path('students/', include('student.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('classes/', include('classes.urls')),
    path('teachers/', include('teachers.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='dashboard/', permanent=True)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

result/urls.py
from django.urls import path, re_path
from result import views

app_name = 'results'

urlpatterns = [
    path('subjectscore/<int:pk>/update/', views.SubjectScoreUpdate.as_view(), name='subject-score-update'),
    path('subjectscore/<int:pk>/delete/', views.SubjectScoreDelete.as_view(), name='subject-score-delete'),
]

student/urls.py
from django.urls import path

from student.views import StudentListView, StudentCreateView, StudentUpdateView, StudentDeleteView, StudentDetailView
from result.views import SubjectScoreCreat

app_name = 'students'

urlpatterns = [
    path('list/', StudentListView.as_view(), name='student_list'),
    path('<int:pk>', StudentDetailView.as_view(), name='student-detail'),
    path('create/', StudentCreateView.as_view(), name='student_create'),
    path('update/<int:pk>', StudentUpdateView.as_view(), name='student_update'),
    path('delete/<int:pk>', StudentDeleteView.as_view(), name='student_delete'),

    path('<int:pk>/addscore/', SubjectScoreCreat.as_view(), name='subject-score-create'),
]

classes/models.py
from django.db import models

# Create your models here.
from django.urls import reverse

from teachers.models import Teacher


class Class(models.Model):
    class_name = models.CharField('Lop', max_length=50, unique=True, error_messages={'unique':"Lop hoc nay da ton tai"})
    giao_vien_CN = models.ForeignKey(Teacher, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Giao vien CN')

    class Meta:
        ordering = ['class_name']

    def __str__(self):
        return self.class_name

    def get_absolute_url(self):
        """Returns the url to access a particular classes instance."""
        return reverse('classes:class-detail', args=[str(self.class_name)])

student/models.py
from datetime import date

import django.utils.timezone
from django.db import models

# Create your models here.
from django.urls import reverse

from classes.models import Class


class Student(models.Model):
    GENDER_CHOICES = (
        ('Nam', 'Nam'),
        ('Nu', 'Nu'),
        ('Khac', 'Khac'),
    )

    student_lastname = models.CharField('Ho va ten dem', max_length=80)
    student_firstname = models.CharField('Ten', max_length=50)
    student_gender = models.CharField('Gioi tinh', max_length=10, choices=GENDER_CHOICES, blank=True, default='Nam')
    student_class = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True, verbose_name='Lop')
    student_email = models.EmailField('Email', blank=True)
    student_date_of_birth = models.DateField('Ngay sinh', default=django.utils.timezone.now)
    student_reg = models.DateField(auto_now_add=True, auto_now=False)

    class Meta:
        ordering = ['student_class', 'student_firstname']

    def __str__(self):
        return f'{self.student_lastname} {self.student_firstname}'

    def get_absolute_url(self):
        """Returns the url to access a particular classes instance."""
        return reverse('students:student-detail', args=[str(self.id)])

classes/forms.py
from django import forms
from django.forms import ModelForm

from classes.models import Class
from student.models import Student


class ClassForm(ModelForm):
    class Meta:
        model = Class
        fields = '__all__'
        widgets = {
            'class_name': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'giao_vien_CN':  forms.Select(attrs={'class': 'form-control form-control-user'}),
        }


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        exclude = ('student_class',)

classes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from classes.forms import ClassForm, StudentForm
from classes.models import Class
from student.models import Student


class ClassListView(ListView):
    model = Class
    template_name = 'class_list.html'


class ClassDetailView(LoginRequiredMixin, DetailView):
    model = Class
    template_name = 'class_detail.html'
    slug_field = 'class_name'
    slug_url_kwarg = 'class_name'


class ClassCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'classes.add_class'
    template_name = 'class_form.html'
    model = Class
    form_class = ClassForm


class ClassDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'classes.delete_class'
    model = Class
    template_name = 'class_confirm_delete.html'
    success_url = reverse_lazy('classes:class-list')
    slug_field = 'class_name'
    slug_url_kwarg = 'class_name'


class ClassUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'classes.change_class'
    model = Class
    form_class = ClassForm
    template_name = 'class_update.html'
    slug_field = 'class_name'
    slug_url_kwarg = 'class_name'
    success_url = reverse_lazy('classes:class-list')


class ClassDetailStudentCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'student.add_student'
    model = Student
    form_class = StudentForm
    template_name = 'student_form.html'

    def form_valid(self, form):
        student_class = get_object_or_404(Class, class_name=self.kwargs['class_name'])
        form.instance.student_class = student_class
        return super(ClassDetailStudentCreate, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse_lazy('classes:class-detail', args=(self.object.student_class,))


class ClassDetailStudentUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'student.change_student'
    model = Student
    form_class = StudentForm
    template_name = 'student_update.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('classes:class-detail', args=(self.object.student_class,))


class ClassDetailStudentDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'student.delete_student'
    model = Student
    template_name = 'student_confirm_delete.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('classes:class-detail', args=(self.object.student_class,))

classes/templates/class_confirm_delete.html
{% extends "base.html" %}

{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h4 class="m-0 font-weight-bold text-primary">Xoa lop hoc?</h4>
        </div>
        <div class="card-body">
            <p>Ban muon xoa lop hoc {{ class }}?</p>
            <form action="" method="post">
                {% csrf_token %}
                <table>
                {{ form.as_table }}
                </table>
                <input type="submit" value="Xoa" class="btn btn-primary btn-user">
                <a href="{% url 'classes:class-list' %}" class="btn btn-secondary btn-user">Huy</a>
            </form>
        </div>
    </div>

{% endblock %}

classes/templates/class_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>lop {{ class.class_name }}</title>
{% endblock %}

{% block header_static %}
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Lop {{ class.class_name }}</h1>
        <p class="mb-4">Giao vien chu nhiem: {% if class.giao_vien_CN %}{{ class.giao_vien_CN }}{% else %}Khong{% endif %}</p>
        <p class="mb-4">Si so: {{ class.student_set.all.count }}</p>
        {% if perms.student.add_student %}
        <a class="mb-4" href="{% url 'classes:class-student-create' class.class_name %}">Them hoc sinh</a>
        {% endif %}

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Ho va ten dem</th>
                                <th>Ten</th>
                                <th>Gioi tinh</th>
                                <th>Ngay sinh</th>
                                <th>Bang diem</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>ID</th>
                                <th>Ho va ten dem</th>
                                <th>Ten</th>
                                <th>Gioi tinh</th>
                                <th>Ngay sinh</th>
                                <th>Bang diem</th>
                                <th></th>
                            </tr>
                        </tfoot>
                        <tbody>
                            {% for student in class.student_set.all %}
                            <tr>
                            <td>{{ student.id }}</td>
                            <td>{{ student.student_lastname }}</td>
                            <td>{{ student.student_firstname }}</td>
                            <td>{{ student.student_gender }}</td>
                            <td>{{ student.student_date_of_birth|date:"d-m-Y" }}</td>
                            <td><a {% if perms.student.view_student %}href="{% url 'students:student-detail' student.id %}"{% endif %}>Chi tiet</a> </td>
                            <td><a {% if perms.student.change_student %}href="{% url 'classes:class-student-update' student.id %}"{% endif %}>Cap nhat</a>
                                | <a {% if perms.student.delete_student %}href="{% url 'classes:class-student-delete' student.id %}"{% endif %}>Xoa</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer_static %}
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
{% endblock %}

classes/templates/class_form.html
{% extends "base.html" %}

{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h4 class="m-0 font-weight-bold text-primary">Them hop hoc</h4>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                <table>
                {{ form.as_table }}
                </table>
                <input type="submit" value="Them lop" class="btn btn-primary btn-user">
            </form>
        </div>
    </div>

{% endblock %}

classes/templates/class_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Danh sach lop hoc</title>
{% endblock %}

{% block header_static %}
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Danh sach lop hoc</h1>
        <p class="mb-4">Tong so lop: {{ class_list.count }}</p>

        {% if perms.classes.add_class %}
        <a class="collapse-item" href="{% url 'classes:class-create' %}">Them lop hoc</a>
        {% endif %}

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Lop</th>
                                <th>Si so</th>
                                <th>Giao vien chu nhiem</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>ID</th>
                                <th>Lop</th>
                                <th>Si so</th>
                                <th>Giao vien chu nhiem</th>
                                <th></th>
                            </tr>
                        </tfoot>
                        <tbody>
                        {% for class in class_list %}
                        <tr>
                            <td>{{ class.id }}</td>
                            <td><a {% if perms.classes.view_class %} href="{{ class.get_absolute_url }}" {% endif %}>{{ class.class_name }}</a></td>
                            <td>{{ class.student_set.all.count }}</td>
                            <td>{{ class.giao_vien_CN }}</td>
                            <td>{% if perms.classes.change_class %}<a class="" href="{% url 'classes:class-update' class.class_name%}">Cap nhat</a>{% endif %} {% if perms.classes.delete_class %}| <a class="" href="{% url 'classes:class-delete' class.class_name %}">Xoa</a>{% endif %}
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer_static %}
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
{% endblock %}

classes/templates/class_update.html
{% extends "base.html" %}

{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h4 class="m-0 font-weight-bold text-primary">Cap nhat thong tin lop {{ class.class_name }}</h4>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                <table>
                {{ form.as_table }}
                </table>
                <a class="btn btn-primary btn-user" href="#" data-toggle="modal" data-target="#UpdateModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Cap nhat
                </a>

                <!-- Confirm Update Modal-->
                <div class="modal fade" id="UpdateModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Xac nhan cap nhat</h5>
                                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                            <div class="modal-body">Cap nhat thong tin lop {{ class.class_name }}</div>
                            <div class="modal-footer">
                                <button class="btn btn-secondary" type="button" data-dismiss="modal">Huy</button>
                                <input type="submit" value="Cap nhat" class="btn btn-primary btn-user">
                            </div>
                        </div>
                    </div>
                </div>

            </form>
        </div>
    </div>


{% endblock %}