django_school_management_system/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordChangeView, PasswordResetDoneView, PasswordResetConfirmView
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

from dashboard.forms import ResetPasswordForm, PasswordChangeForm, SetPasswordForm
from dashboard.views import registeruser, editprofile, loginrequest

urlpatterns = [
    path('admin/', admin.site.urls),
    path("login/", loginrequest, name="loginrequest"),
    path("register/", registeruser, name="register"),
    path('editprofile/', editprofile, name='editprofile'),
    path('changepassword/', PasswordChangeView.as_view(template_name='registration/changepassword.html', form_class=PasswordChangeForm, success_url=reverse_lazy('dashboard:dashboard')), name='changepassword'),
    path('passwordreset/', PasswordResetView.as_view(template_name='registration/resetpassword.html', form_class=ResetPasswordForm, success_url=reverse_lazy('passwordresetsendmail')), name='resetpassword'),
    path('passwordresetmail/', PasswordResetDoneView.as_view(template_name='registration/sendmailnoti.html'), name='passwordresetsendmail'),
    path('setnewpassword/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/setnewpassword.html', form_class=SetPasswordForm, success_url=reverse_lazy('password_reset_complete')), name='setnewpassword'),

    path('results/', include('result.urls')),
    path('subjects/', include('subjects.urls')),
    path('students/', include('student.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('classes/', include('classes.urls')),
    path('teachers/', include('teachers.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='dashboard/', permanent=True)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

result/urls.py
from django.urls import path, re_path
from result import views

app_name = 'results'

urlpatterns = [
    path('subjectscore/<int:pk>/update/', views.SubjectScoreUpdate.as_view(), name='subject-score-update'),
    path('subjectscore/<int:pk>/delete/', views.SubjectScoreDelete.as_view(), name='subject-score-delete'),
]

student/urls.py
from django.urls import path

from student.views import StudentListView, StudentCreateView, StudentUpdateView, StudentDeleteView, StudentDetailView
from result.views import SubjectScoreCreat

app_name = 'students'

urlpatterns = [
    path('list/', StudentListView.as_view(), name='student_list'),
    path('<int:pk>', StudentDetailView.as_view(), name='student-detail'),
    path('create/', StudentCreateView.as_view(), name='student_create'),
    path('update/<int:pk>', StudentUpdateView.as_view(), name='student_update'),
    path('delete/<int:pk>', StudentDeleteView.as_view(), name='student_delete'),

    path('<int:pk>/addscore/', SubjectScoreCreat.as_view(), name='subject-score-create'),
]

result/models.py
from django.db import models

# Create your models here.
from student.models import Student
from subjects.models import Subject


def convert(x):
    return [float(i) for i in x.split()]


class SubjectScore(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name="Hoc sinh")
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, verbose_name="Mon hoc")
    diem_he_so_1 = models.CharField(max_length=40, blank=True)
    diem_he_so_2 = models.CharField(max_length=40, blank=True)
    diem_he_so_3 = models.CharField(max_length=40, blank=True)

    class Meta:
        unique_together = ('student', 'subject',)
        ordering = ['subject']

    def diemTB(self):
        if self.diem_he_so_1 and self.diem_he_so_2 and self.diem_he_so_3:
            return round((sum(convert(self.diem_he_so_1)) + sum(convert(self.diem_he_so_2)) * 2 + sum(convert(self.diem_he_so_3)) * 3) / (
                    len(convert(self.diem_he_so_1)) + len(convert(self.diem_he_so_2)) * 2 + len(convert(self.diem_he_so_3)) * 3),2)
        else:
            return ''

    def phanloai(self):
        if not self.diemTB():
            return ''
        elif self.diemTB() >= 8:
            return "Gioi"
        elif self.diemTB() >= 7:
            return "Kha"
        elif self.diemTB() >= 6:
            return "Trung binh"
        else:
            return "Yeu"

    def __str__(self):
        return f'{self.student}: Diem mon {self.subject}'

student/models.py
from datetime import date

import django.utils.timezone
from django.db import models

# Create your models here.
from django.urls import reverse

from classes.models import Class


class Student(models.Model):
    GENDER_CHOICES = (
        ('Nam', 'Nam'),
        ('Nu', 'Nu'),
        ('Khac', 'Khac'),
    )

    student_lastname = models.CharField('Ho va ten dem', max_length=80)
    student_firstname = models.CharField('Ten', max_length=50)
    student_gender = models.CharField('Gioi tinh', max_length=10, choices=GENDER_CHOICES, blank=True, default='Nam')
    student_class = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True, verbose_name='Lop')
    student_email = models.EmailField('Email', blank=True)
    student_date_of_birth = models.DateField('Ngay sinh', default=django.utils.timezone.now)
    student_reg = models.DateField(auto_now_add=True, auto_now=False)

    class Meta:
        ordering = ['student_class', 'student_firstname']

    def __str__(self):
        return f'{self.student_lastname} {self.student_firstname}'

    def get_absolute_url(self):
        """Returns the url to access a particular classes instance."""
        return reverse('students:student-detail', args=[str(self.id)])

student/forms.py
from django import forms
from django.forms import ModelForm

from student.models import Student


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'
        widgets = {
            'student_lastname': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'student_firstname': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'student_gender': forms.Select(attrs={'class': 'form-control form-control-user'}),
            'student_class': forms.Select(attrs={'class': 'form-control form-control-user'}),
            'student_email': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'student_date_of_birth': forms.DateInput(attrs={'class': 'form-control form-control-user'}),
            'giao_vien_CN':  forms.Select(attrs={'class': 'form-control form-control-user'}),
        }

student/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView, ListView, DetailView

from result.models import SubjectScore
from student.forms import StudentForm
from student.models import Student
from subjects.models import Subject


class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    template_name = 'student_list.html'


def phanloai(x):
    if x == '':
        return ''
    elif x >= 8:
        return "Gioi"
    elif x >= 7:
        return "Kha"
    elif x >= 6:
        return "Trung binh"
    else:
        return "Yeu"


class StudentDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    permission_required = 'student.view_student'
    model = Student
    template_name = 'student_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        hoc_sinh = get_object_or_404(Student, id=self.kwargs['pk'])
        list_diemTB = [mon.diemTB() for mon in hoc_sinh.subjectscore_set.all()]
        if all(list_diemTB) and len(list_diemTB) > 0:
            diem_TB_tong = round(sum(list_diemTB) / len(list_diemTB), 2)
            context['diem_TB_tong'] = diem_TB_tong
            context['phan_loai_chung'] = phanloai(diem_TB_tong)
        return context


class StudentCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'student.add_student'
    template_name = 'student_form.html'
    model = Student
    form_class = StudentForm
    success_url = reverse_lazy('students:student_list')

    def form_valid(self, form):
        student = super(StudentCreateView, self).form_valid(form)
        for subject in Subject.objects.all():
            SubjectScore.objects.create(subject=subject, student=self.object)
        return student


class StudentDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = 'student.delete_student'
    model = Student
    template_name = 'student_confirm_delete.html'
    success_url = reverse_lazy('students:student_list')


class StudentUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'student.change_student'
    model = Student
    form_class = StudentForm
    template_name = 'student_update.html'
    success_url = reverse_lazy('students:student_list')

student/templates/student_confirm_delete.html
{% extends "base.html" %}

{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h4 class="m-0 font-weight-bold text-primary">Xoa thong tin hoc sinh?</h4>
        </div>
        <div class="card-body">
            <p>Ban muon xoa thong tin cua hoc sinh {{ student }}?</p>
            <form action="" method="post">
                {% csrf_token %}
                <table>
                {{ form.as_table }}
                </table>
                <input type="submit" value="Xoa" class="btn btn-primary btn-user">
                <a href="{% url 'students:student_list' %}" class="btn btn-secondary btn-user">Huy</a>
            </form>
        </div>
    </div>

{% endblock %}

student/templates/student_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Thong tin hoc sinh</title>
{% endblock %}

{% block header_static %}
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Hoc sinh: {{ student.student_lastname }} {{ student.student_firstname }}</h1>
        <p class="mb-4">Gioi tinh: {{ student.student_gender }}</p>
        <p class="mb-4">Lop: {{ student.student_class }}</p>
        <p class="mb-4">Ngay sinh: {{ student.student_date_of_birth|date:"d-m-Y" }}</p>
        {% if diem_TB_tong %}
        <p>Diem chung binh chung: {{ diem_TB_tong }} - Phan loai chung: {{ phan_loai_chung }}</p>
        {% endif %}
        {% if perms.student.add_student %}
            <p><a href="{% url 'students:subject-score-create' student.id %}">Them diem cac mon</a> </p>
        {% endif %}

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>Mon hoc</th>
                                <th>Diem he so 1</th>
                                <th>Diem he so 2</th>
                                <th>Diem he so 3</th>
                                <th>Diem TB</th>
                                <th>Phan loai</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>STT</th>
                                <th>Mon hoc</th>
                                <th>Diem he so 1</th>
                                <th>Diem he so 2</th>
                                <th>Diem he so 3</th>
                                <th>Diem TB</th>
                                <th>Phan loai</th>
                                <th></th>
                            </tr>
                        </tfoot>
                        <tbody>
                            {% for score in student.subjectscore_set.all %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ score.subject }}</td>
                                <td>{{ score.diem_he_so_1 }}</td>
                                <td>{{ score.diem_he_so_2 }}</td>
                                <td>{{ score.diem_he_so_3 }}</td>
                                <td>{{ score.diemTB }}</td>
                                <td>{{ score.phanloai }}</td>
                                <td><a href="{% url 'results:subject-score-update' score.id %}">Cap nhat</a> | <a href="{% url 'results:subject-score-delete' score.id %}">Xoa</a> </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer_static %}
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
{% endblock %}

student/templates/student_form.html
{% extends "base.html" %}

{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h4 class="m-0 font-weight-bold text-primary">Them hoc sinh</h4>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                <table>
                {{ form.as_table }}
                </table>
                <input type="submit" value="Them hoc sinh" class="btn btn-primary btn-user">
            </form>
        </div>
    </div>

{% endblock %}

student/templates/student_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Danh sach hoc sinh</title>
{% endblock %}

{% block header_static %}
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="container-fluid">

        <!-- Page Heading -->
        <h1 class="h3 mb-2 text-gray-800">Danh sach hoc sinh</h1>
        <p class="mb-4">Tong so hoc sinh: {{ student_list.count }}</p>

        {% if perms.student.add_student %}
        <a class="collapse-item" href="{% url 'students:student_create' %}">Them hoc sinh</a>
        {% endif %}

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Ho va ten dem</th>
                                <th>Ten</th>
                                <th>Gioi tinh</th>
                                <th>Lop</th>
                                <th>Ngay sinh</th>
                                <th>Bang diem</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>ID</th>
                                <th>Ho va ten dem</th>
                                <th>Ten</th>
                                <th>Gioi tinh</th>
                                <th>Lop</th>
                                <th>Ngay sinh</th>
                                <th>Bang diem</th>
                                <th></th>
                            </tr>
                        </tfoot>
                        <tbody>
                        {% for student in student_list %}
                        <tr>
                            <td>{{ student.id }}</td>
                            <td>{{ student.student_lastname }}</td>
                            <td>{{ student.student_firstname }}</td>
                            <td>{{ student.student_gender }}</td>
                            <td>{{ student.student_class }}</td>
                            <td>{{ student.student_date_of_birth|date:"d-m-Y" }}</td>
                            <td><a {% if perms.student.view_student %} href="{{ student.get_absolute_url }}" {% endif %}>Chi tiet</a></td>
                            <td>{% if perms.student.change_student %}<a class="" href="{% url 'students:student_update' student.id %}">Cap nhat</a>{% endif %} {% if perms.student.delete_student %}| <a class="" href="{% url 'students:student_delete' student.id %}">Xoa</a>{% endif %}
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer_static %}
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
{% endblock %}

student/templates/student_update.html
{% extends "base.html" %}

{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h4 class="m-0 font-weight-bold text-primary">Cap nhat thong tin hoc sinh {{ student.student_lastname }} {{ student.student_firstname }}</h4>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                <table>
                {{ form.as_table }}
                </table>
                <a class="btn btn-primary btn-user" href="#" data-toggle="modal" data-target="#UpdateModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Cap nhat
                </a>

                <!-- Confirm Update Modal-->
                <div class="modal fade" id="UpdateModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Xac nhan cap nhat</h5>
                                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                            <div class="modal-body">Cap nhat thong tin hoc sinh {{ student.student_lastname }} {{ student.student_firstname }}</div>
                            <div class="modal-footer">
                                <button class="btn btn-secondary" type="button" data-dismiss="modal">Huy</button>
                                <input type="submit" value="Cap nhat" class="btn btn-primary btn-user">
                            </div>
                        </div>
                    </div>
                </div>

            </form>
        </div>
    </div>


{% endblock %}