classes/urls.py
from django.urls import path, re_path
from classes import views

app_name = 'classes'

urlpatterns = [
    path('list/', views.ClassListView.as_view(), name='class-list'),
    re_path(r'^(?P<class_name>[-\w]+)$', views.ClassDetailView.as_view(), name='class-detail'),
    path('create/', views.ClassCreateView.as_view(), name='class-create'),
    re_path(r'^(?P<class_name>[-\w]+)/update/$', views.ClassUpdateView.as_view(), name='class-update'),
    re_path(r'^(?P<class_name>[-\w]+)/delete/$', views.ClassDeleteView.as_view(), name='class-delete'),

    re_path(r'^(?P<class_name>[-\w]+)/addstudent/$', views.ClassDetailStudentCreate.as_view(), name='class-student-create'),
    path('deletestudent/<int:pk>', views.ClassDetailStudentDelete.as_view(), name='class-student-delete'),
    path('updatestudent/<int:pk>', views.ClassDetailStudentUpdate.as_view(), name='class-student-update'),
]

dashboard/urls.py
from django.urls import path

from dashboard.views import Dashboard

app_name = 'dashboard'

urlpatterns = [
    path('', Dashboard.as_view(), name='dashboard'),
]

django_school_management_system/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordChangeView, PasswordResetDoneView, PasswordResetConfirmView
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

from dashboard.forms import ResetPasswordForm, PasswordChangeForm, SetPasswordForm
from dashboard.views import registeruser, editprofile, loginrequest

urlpatterns = [
    path('admin/', admin.site.urls),
    path("login/", loginrequest, name="loginrequest"),
    path("register/", registeruser, name="register"),
    path('editprofile/', editprofile, name='editprofile'),
    path('changepassword/', PasswordChangeView.as_view(template_name='registration/changepassword.html', form_class=PasswordChangeForm, success_url=reverse_lazy('dashboard:dashboard')), name='changepassword'),
    path('passwordreset/', PasswordResetView.as_view(template_name='registration/resetpassword.html', form_class=ResetPasswordForm, success_url=reverse_lazy('passwordresetsendmail')), name='resetpassword'),
    path('passwordresetmail/', PasswordResetDoneView.as_view(template_name='registration/sendmailnoti.html'), name='passwordresetsendmail'),
    path('setnewpassword/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/setnewpassword.html', form_class=SetPasswordForm, success_url=reverse_lazy('password_reset_complete')), name='setnewpassword'),

    path('results/', include('result.urls')),
    path('subjects/', include('subjects.urls')),
    path('students/', include('student.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('classes/', include('classes.urls')),
    path('teachers/', include('teachers.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='dashboard/', permanent=True)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

result/urls.py
from django.urls import path, re_path
from result import views

app_name = 'results'

urlpatterns = [
    path('subjectscore/<int:pk>/update/', views.SubjectScoreUpdate.as_view(), name='subject-score-update'),
    path('subjectscore/<int:pk>/delete/', views.SubjectScoreDelete.as_view(), name='subject-score-delete'),
]

student/urls.py
from django.urls import path

from student.views import StudentListView, StudentCreateView, StudentUpdateView, StudentDeleteView, StudentDetailView
from result.views import SubjectScoreCreat

app_name = 'students'

urlpatterns = [
    path('list/', StudentListView.as_view(), name='student_list'),
    path('<int:pk>', StudentDetailView.as_view(), name='student-detail'),
    path('create/', StudentCreateView.as_view(), name='student_create'),
    path('update/<int:pk>', StudentUpdateView.as_view(), name='student_update'),
    path('delete/<int:pk>', StudentDeleteView.as_view(), name='student_delete'),

    path('<int:pk>/addscore/', SubjectScoreCreat.as_view(), name='subject-score-create'),
]

subjects/urls.py
from django.urls import path

from subjects.views import SubjectListView, SubjectDetailView, SubjectCreateView, SubjectUpdateView, SubjectDeleteView

app_name = 'subjects'

urlpatterns = [
    path('', SubjectListView.as_view(), name='subject_list'),
    path('<int:pk>', SubjectDetailView.as_view(), name='subject-detail'),
    path('create/', SubjectCreateView.as_view(), name='subject_create'),
    path('update/<int:pk>', SubjectUpdateView.as_view(), name='subject_update'),
    path('delete/<int:pk>', SubjectDeleteView.as_view(), name='subject_delete'),
]

teachers/urls.py
from django.urls import path, re_path
from teachers import views

app_name = 'teachers'

urlpatterns = [
    path('list/', views.TeacherListView.as_view(), name='teacher-list'),
    path('<int:pk>', views.TeacherDetailView.as_view(), name='teacher-detail'),
    path('create/', views.TeacherCreateView.as_view(), name='teacher-create'),
    path('update/<int:pk>', views.TeacherUpdateView.as_view(), name='teacher-update'),
    path('delete/<int:pk>', views.TeacherDeleteView.as_view(), name='teacher-delete'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm, PasswordResetForm, \
    SetPasswordForm
from django.contrib.auth.models import User
import re


class NewUserForm(UserCreationForm):
    email = forms.EmailField(label="Email",
                             widget=forms.TextInput(attrs={'class': 'form-control form-control-user', 'placeholder': 'Nhap email'}))
    last_name = forms.CharField(label="Ho", max_length=100,
                                widget=forms.TextInput(attrs={'class': 'form-control form-control-user', 'placeholder': 'Nhap ho'}))
    first_name = forms.CharField(label="Ten", max_length=100,
                                 widget=forms.TextInput(attrs={'class': 'form-control form-control-user', 'placeholder': 'Nhap ten'}))

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control form-control-user'
        self.fields['username'].widget.attrs['placeholder'] = 'Nhap ten nguoi dung'
        self.fields['username'].label = 'Ten nguoi dung'
        self.fields['username'].help_text = ''

        self.fields['password1'].widget.attrs['class'] = 'form-control form-control-user'
        self.fields['password1'].widget.attrs['placeholder'] = 'Nhap mat khau'
        self.fields['password1'].label = 'Nhap mat khau'
        self.fields['password1'].help_text = ''

        self.fields['password2'].widget.attrs['class'] = 'form-control form-control-user'
        self.fields['password2'].widget.attrs['placeholder'] = 'Xac nhan mat khau'
        self.fields['password2'].label = 'Nhap lai mat khau'
        self.fields['password2'].help_text = ''

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2 and password1:
                return password2
        raise forms.ValidationError("Mat khau khong trung khop")

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^(?=.{8,20}$)(?![_.])(?!.*[_.]{2})[a-zA-Z0-9._]+(?<![_.])$', username):
            raise forms.ValidationError("Tên tài khoản có kí tự đặc biệt")
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError("Tài khoản đã tồn tại")

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError('Email da duoc dang ky. Vui long chon email khac')

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class UserChangeForm(UserChangeForm):
    email = forms.EmailField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control form-control-user', 'type':'email'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control form-control-user'}))
    first_name = forms.CharField( max_length=100, widget=forms.TextInput(attrs={'class':'form-control form-control-user'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        super(UserChangeForm, self).__init__(*args, **kwargs)
        self.fields['password'].label = ''
        self.fields['password'].help_text= "<a href=\"../changepassword/\">Thay doi mat khau</a>"


class PasswordChangeForm(PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].widget.attrs['class'] = 'form-control form-control-user'
        self.fields['old_password'].widget.attrs['placeholder'] = 'Mat khau cu'
        self.fields['old_password'].label = 'Nhap mat khau cu'

        self.fields['new_password1'].widget.attrs['class'] = 'form-control form-control-user'
        self.fields['new_password1'].widget.attrs['placeholder'] = 'Mat khau moi'
        self.fields['new_password1'].label = 'Nhap mat khau moi'
        self.fields['new_password1'].help_text=['Mật khẩu của bạn không được quá giống với thông tin cá nhân khác của bạn', 'Mật khẩu của bạn phải chứa ít nhất 8 ký tự', 'Mật khẩu của bạn không thể là mật khẩu thường dùng', 'Mật khẩu của bạn không được hoàn toàn là số']

        self.fields['new_password2'].widget.attrs['class'] = 'form-control form-control-user'
        self.fields['new_password2'].widget.attrs['placeholder'] = 'Xac nhan mat khau'
        self.fields['new_password2'].label = 'Nhap mat lai khau'

        self.error_messages['password_incorrect'] = "Mật khẩu cũ của bạn đã được nhập không chính xác. Vui lòng nhập " \
                                                    "lại. "
        self.error_messages['password_mismatch'] = 'Hai trường mật khẩu không khớp.'


class ResetPasswordForm(PasswordResetForm):

    def __init__(self, *args, **kwargs):
        super(ResetPasswordForm, self).__init__(*args, **kwargs)

    email = forms.EmailField(
        label="Email",
        max_length=254,
        widget=forms.EmailInput(attrs={'autocomplete': 'email', 'class': 'form-control form-control-user', 'placeholder':'Nhap email'})
    )


class SetPasswordForm(SetPasswordForm):

    def __init__(self, *args, **kwargs):
        super(SetPasswordForm, self).__init__(*args, **kwargs)

        self.fields['new_password1'].widget.attrs['class'] = 'form-control form-control-user'
        self.fields['new_password1'].widget.attrs['placeholder'] = 'Mat khau moi'
        self.fields['new_password1'].label = 'Nhap mat khau moi'
        self.fields['new_password1'].help_text=['Mật khẩu của bạn không được quá giống với thông tin cá nhân khác của bạn', 'Mật khẩu của bạn phải chứa ít nhất 8 ký tự', 'Mật khẩu của bạn không thể là mật khẩu thường dùng', 'Mật khẩu của bạn không được hoàn toàn là số']

        self.fields['new_password2'].widget.attrs['class'] = 'form-control form-control-user'
        self.fields['new_password2'].widget.attrs['placeholder'] = 'Xac nhan mat khau'
        self.fields['new_password2'].label = 'Nhap mat lai khau'

        self.error_messages['password_mismatch'] = 'Hai trường mật khẩu không khớp.'

dashboard/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
import re
# Create your views here.
from django.views.generic import TemplateView

from classes.models import Class
from dashboard.forms import NewUserForm, UserChangeForm, PasswordChangeForm, PasswordResetForm
from student.models import Student
from teachers.models import Teacher
from subjects.models import Subject


class HomePageView(TemplateView):
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['num_student'] = Student.objects.all().count()
        context['num_teacher'] = Teacher.objects.all().count()
        context['num_class'] = Class.objects.all().count()
        return context


def loginrequest(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('dashboard:dashboard')
        else:
            messages.error(request, 'Ten tai khoang va mat khau khong hop le')
    return render(request, 'registration/login.html')


def registeruser(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            user_name = form.cleaned_data['username']
            pass_word = form.cleaned_data['password1']
            user_obj = authenticate(request, username=user_name, password = pass_word)
            login(request, user_obj)
            messages.success(request, "Dang ky tai khoan thanh cong", extra_tags='green')
            # return redirect('login')
        else:
            messages.error(request, 'Dang ky tai khoan khong thanh cong')
    else:
        form = NewUserForm()
    context = {'form':form}
    return render(request, 'registration/register.html', context)


def editprofile(request):
    if request.method == "POST":
        form = UserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, ("Cap nhat thong tin tai khoan thanh cong"))
        else:
            messages.error(request, 'Cap nhat thong tin khong thanh cong')
    else:
        form = UserChangeForm(instance=request.user)
    context = {'form': form}
    return render(request, 'registration/editprofile.html', context)


# def changepassword(request):
#     if request.method == "POST":
#         form = PasswordChangeForm(data=request.POST, user=request.user)
#         if form.is_valid():
#             form.save()
#             messages.success(request, "Thay doi mat khau thanh cong", extra_tags='green')
#         else:
#             messages.error(request, 'Thay doi mat khau khong thanh cong')
#     else:
#         form = PasswordChangeForm(user=request.user)
#     context = {'form': form}
#     return render(request, 'registration/changepassword.html', context)


# def resetpassword(request):
#     if request.method == 'POST':
#         form = PasswordResetForm(request.POST)
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'Da gui mail')
#         else:
#             messages.error(request, 'Gui mail xac thuc khong thanh cong')
#     else:
#         form = PasswordResetForm()
#     context = {'form': form}
#     return render(request, 'registration/resetpassword.html', context)

class Dashboard(TemplateView):
    template_name = 'dashboard.html'

    gender_male = Student.objects.filter(student_gender="Nam").count()
    gender_female = Student.objects.filter(student_gender="Nu").count()
    gender_other = Student.objects.filter(student_gender="Khac").count()
    gender_list = [gender_male, gender_female, gender_other]

    student_all = Student.objects.all()
    class_all = Class.objects.all()

    grade_list = sorted({re.split('[a-zA-Z]', one_class.class_name, 1)[0] for one_class in class_all})
    grade_name_list = ['Khoi ' + grade for grade in grade_list]
    student_in_grade_count_list = []
    for grade in grade_list:
        students = Student.objects.filter(student_class__class_name__istartswith=grade).count()
        student_in_grade_count_list.append(students)

    panel_list = sorted({re.findall('[a-zA-Z]', one_class.class_name)[0] for one_class in class_all})
    panel_list_name = ['Ban ' + panel for panel in panel_list]
    student_in_panel_count_list = []
    for panel in panel_list:
        students = Student.objects.filter(student_class__class_name__contains=panel).count()
        student_in_panel_count_list.append(students)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['num_student'] = Student.objects.all().count()
        context['num_teacher'] = Teacher.objects.all().count()
        context['num_class'] = Class.objects.all().count()
        context['num_subject'] = Subject.objects.all().count()
        context['gender_list'] = self.gender_list

        context['grade_name_list'] = self.grade_name_list
        context['student_in_grade_count_list'] = self.student_in_grade_count_list

        context['panel_list_name'] = self.panel_list_name
        context['student_in_panel_count_list'] = self.student_in_panel_count_list
        return context

dashboard/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}
<title>Trang chu</title>
{% endblock %}

{% block style %}

{% endblock %}

{% block content %}

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
    </div>

    <!-- Content Row -->
    <div class="row">

        <!-- Hoc sinh Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                So hoc sinh</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ num_student }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-address-card fa-2x text-gray-300"></i>
                        </div>
                    </div>
                    <div class="row no-gutters align-items-center">
                        <a href="{% url 'students:student_list' %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Lop hoc Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                So lop hoc</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ num_class }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-users fa-2x text-gray-300"></i>
                        </div>
                    </div>
                    <div class="row no-gutters align-items-center">
                        <a href="{% url 'classes:class-list' %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Lop hoc Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                So mon hoc</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ num_subject }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-book fa-2x text-gray-300"></i>
                        </div>
                    </div>
                    <div class="row no-gutters align-items-center">
                        <a href="{% url 'subjects:subject_list' %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Pending Requests Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                So giao vien</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ num_teacher }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-user-circle fa-2x text-gray-300"></i>
                        </div>
                    </div>
                    <div class="row no-gutters align-items-center">
                        <a href="{% url 'teachers:teacher-list' %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <!-- Student - Teacher Chart -->
        <div class="col-xl-6 col-lg-6">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Hoc sinh va Giao vien</h6>

                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                            aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Tuy chon:</div>
                            <a class="dropdown-item" href="{% url 'students:student_list' %}">Danh sach hoc sinh</a>
                            <a class="dropdown-item" href="{% url 'teachers:teacher-list' %}">Danh sach giao vien</a>
                        </div>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body" style="min-height: 330px; height: 300px; max-height: 250px; max-width: 100%;">
                    <div class="chart-pie">
                        <canvas id="StudentTeacherPieChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                    </div>
                </div>
            </div>
        </div>

        <!-- Student gender Chart -->
        <div class="col-xl-6 col-lg-6">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Hoc sinh</h6>

                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                            aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Tuy chon:</div>
                            <a class="dropdown-item" href="{% url 'students:student_list' %}">Danh sach hoc sinh</a>
                            <a class="dropdown-item" href="{% url 'students:student_create' %}">Them hoc sinh</a>
                        </div>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body" style="min-height: 330px; height: 300px; max-height: 250px; max-width: 100%;">
                    <div class="chart-pie">
                        <canvas id="StudentGenderPieChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="row">
        <!-- Students in grade Chart -->
        <div class="col-xl-6 col-lg-6">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Hoc sinh cac khoi</h6>

                    <div class="card-tools">
                      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                      <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-pie">
                        <canvas id="StudentGradePieChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                    </div>
                </div>
            </div>
        </div>

        <!-- Students in Panel Chart -->
        <div class="col-xl-6 col-lg-6">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Hoc sinh cac ban</h6>

                    <div class="card-tools">
                      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                      <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                    </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-pie">
                        <canvas id="StudentPanelPieChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block custom_js %}
<script>
    {#Student - Teacher Chart#}
    const studentAndTeacher = document.getElementById("StudentTeacherPieChart").getContext('2d');
    const studentAndTeacherChart = new Chart(studentAndTeacher, {
        type: 'pie',
        data: {
            labels: ["Hoc sinh", "Giao vien"],
            datasets: [{
                data: [{{ num_student }}, {{ num_teacher }}],
                backgroundColor: ["#F7464A", "#46BFBD"],
                hoverBackgroundColor: ["#FF5A5E", "#5AD3D1"]
            }]
        },
        options: {
            responsive: true
        }
    });

    {#Student gender chart#}
    const studentGender = document.getElementById("StudentGenderPieChart").getContext('2d');
    const studentGenderChart = new Chart(studentGender, {
        type: 'doughnut',
        data: {
            labels: ["Nam", "Nu", 'Khac'],
            datasets: [{
                data: {{ gender_list }},
                backgroundColor: ["#FDB45C", "#949FB1", "#4D5360"],
                hoverBackgroundColor: ["#FFC870", "#A8B3C5", "#616774"]
            }]
        },
        options: {
            responsive: true
        }
    });

    {#Student - Grade Chart#}
    const studentGrade = document.getElementById("StudentGradePieChart").getContext('2d');
    const studentGradeChart = new Chart(studentGrade, {
        type: 'pie',
        data: {
            labels: {{ grade_name_list|safe }},
            datasets: [{
                data: {{ student_in_grade_count_list }},
                backgroundColor: ["#0311ff", "#1ab5b4", "#ff4a32"],
                hoverBackgroundColor: ["#5861ff", "#1fd2d1", "#ff7765"]
            }]
        },
        options: {
            responsive: true
        }
    });

    {#Student - Panel Chart#}
    const studentPanel = document.getElementById("StudentPanelPieChart").getContext('2d');
    const studentPanelChart = new Chart(studentPanel, {
        type: 'pie',
        data: {
            labels: {{ panel_list_name|safe }},
            datasets: [{
                data: {{ student_in_panel_count_list }},
                backgroundColor: ["#913a90", "#ffc52d", "#33f131"],
                hoverBackgroundColor: ["#b548b4", "#ffce4f", "#52f351"]
            }]
        },
        options: {
            responsive: true
        }
    });

</script>

{% endblock %}